### ISSUE TITLE
Use clsx instead of classNames

### ISSUE THREAD

**Issue by lopezjurip** [muhammadsammy/tailwindcss-classnames#126]
This module is a drop-in replacement but smaller and faster.
https://github.com/lukeed/clsx

**Comment by muhammadsammy** [comment]
This seems like a better alternative. Thanks for the suggestion!

**Comment by imrishabh18** [comment]
@muhammadsammy Can I take up this issue? And what do I need to do. Remove the classnames dependency and add the clsx in place of that?

**Comment by muhammadsammy** [comment]
You 're welcome! 
I believe this would do it + modifying the import statement in template string generation in the CLI too.

**Comment by imrishabh18** [comment]
![image](https://user-images.githubusercontent.com/38923768/117217268-bbec2780-ae1e-11eb-8733-4eeada8cf8a0.png)

I have replaced the import statements and generated the file successfully, but while running `yarn run-cli` I don't know what should I give as path for the custom files types.

**Comment by muhammadsammy** [comment]
This is optional for adding additional types if you have them in a file. just leave it empty
but the error is showing that tailwind.config.js can't be found. did you run `npx tailwindcss init`?
