### ISSUE TITLE
Please push latest changes to npm

### ISSUE THREAD

**Issue by darkship** [muhammadsammy/tailwindcss-classnames#129]
## Environment:

- `tailwindcss`: "^2.0.2",
- `tailwindcss-classnames`: "^2.0.0"
- `Node.js` version: 14.7.0

## Current Behavior
darkmode prefix isn't recognized
`TS2345: Argument of type '"dark:bg-gray-400"' is not assignable to parameter of type 'TArg'.`

## Expected Behavior
darkmode prefix is recognized.

## How to Reproduce
tw( 'dark:bg-gray-400',)

## Possible solutions (Optional)
Push latest change to npm

**Comment by muhammadsammy** [comment]
Thanks for reporting!

The regular npm package contains types for the default tailwindcss classnames. Dark mode is disabled in TailwindCSS by default.

From the [docs](https://tailwindcss.com/docs/dark-mode):
>**It's important to note that because of file size considerations, the dark mode variant is not enabled in Tailwind by default.**
>

To enable the types for dark mode, make sure that `darkMode` is set to **"class"** or **"media"** as stated in the docs and use the [`tailwindcss-classnames` CLI](https://github.com/muhammadsammy/tailwindcss-classnames#using-the-cli-to-generate-custom-types) to generate the types for your custom tailwind config.

**Comment by darkship** [comment]
hey, thanks for the reply, I found the issue. I had to recreate the types after activating the dark mode
