### ISSUE TITLE
PurgeCSS removes all pseudo selector classes

### ISSUE THREAD

**Issue by muhammadsammy** [muhammadsammy/tailwindcss-classnames#13]
PurgeCSS removes classes generated by pseudo selector functions as `hover()`, `md()` even if they are being used.

**Comment by muhammadsammy** [comment]
The solution that comes to my mind is that: 
Instead of using the pseudo class methods like `hover()` and `md()`, the pseudo classes will be added to the types as normal strings e.g. `md:bg-red-500`, `focus:bg-red-700`,.. depending on the tailwind config's [`theme.variants`](https://tailwindcss.com/docs/configuring-variants).
Also, this would be more type safe as these methods accept any tailwind class whether it's available with the pseudo selector or not.

**Comment by AdrienLemaire** [comment]
That seems to also be postcss-ts-classnames' approach :+1:

**Comment by muhammadsammy** [comment]
Fixed in version 1.3.1
