### ISSUE TITLE
configuration file parameter

### ISSUE THREAD

**Issue by AdrienLemaire** [muhammadsammy/tailwindcss-classnames#14]
Hi @muhammadsammy , I just found out about this project, and it looks great so I'll start using it right away :)

Can you let us specify the tailwind.config.js file and only fall back to the inquirer prompt when the parameter is missing?
I'd like to get my types auto-updated when starting the devServer.

```json
{
  "scripts": {
    "start": "npm run build:types && npm run build:css && npm run dev",
    "build:types": "tailwindcss-classnames --config ./src/tailwind.js"
  }
}
```

Unrelated question: Have you been monitoring performances using your library? I'm a bit concerned about the overhead at runtime and bundle size.
Ideally, I'd like a webpack plugin to execute the tailwindcss-classnames related code and convert it to dumb strings as it'd be without this library (resulting in a zero footprint).
Any thoughts on this?

**Comment by muhammadsammy** [comment]
Hello, Adrien!
Thanks for your suggestions!

> Can you let us specify the tailwind.config.js file and only fall back to the inquirer prompt when the parameter is missing?
> I'd like to get my types auto-updated when starting the devServer.
>
Sure, it would be nicer than manually calling the command every time the config changes.

> Unrelated question: Have you been monitoring performances using your library? I'm a bit concerned about the overhead at runtime and bundle size.
>
This package is just the `classnames` package with types for TailwindCSS so it's around [422B](https://bundlephobia.com/result?p=classnames@2.2.6).
Regarding performance here is what the [classnames project says].(https://github.com/JedWatson/classnames#project-philosophy)

> Ideally, I'd like a webpack plugin to execute the tailwindcss-classnames related code and convert it to dumb strings as it'd be without this library (resulting in a zero footprint).
> Any thoughts on this?
>
If you generated the types in a custom file and it's included in the project, Wouldn't webpack handle it as a normal TS file?

**Comment by muhammadsammy** [comment]
The feature has been added in 308346c
