### ISSUE TITLE
missing type for default color

### ISSUE THREAD

**Issue by AdrienLemaire** [muhammadsammy/tailwindcss-classnames#15]
given the tailwind config:
```js
module.exports = {
    colors: {
      transparent: "transparent",
      current: "currentColor",

      blue: {
        default: "#0099D7",
        lighter: lighten("#0099D7", 0.1),
      },
}
```

We can add the class "bg-blue-lighten" and "bg-blue" (notice the lack of '-default' suffix).

From https://tailwindcss.com/docs/customizing-colors#nested-object-syntax

> Like many other places in Tailwind, the default key is special and means "no modifier"

tailwindcss-classnames will generate the following types:
```ts
export type TBackgroundColor =
  | 'bg-transparent'
  | 'bg-current'
  | 'bg-blue-default'
  | 'bg-blue-lighter'
```

Can you make it so it generate the following instead?
```ts
export type TBackgroundColor =
  | 'bg-transparent'
  | 'bg-current'
  | 'bg-blue'
  | 'bg-blue-default'
  | 'bg-blue-lighter'
```

**Comment by AdrienLemaire** [comment]
Another issue: when forcing `-default` on my classes, I'm getting the following two errors

> tsserver 2345] [E] Argument of type '"bg-blue-default"' is not assignable to parameter of type 'TArgs<TClasses>'
> tsserver 2345] [E] Argument of type '"bg-blue-lighter"' is not assignable to parameter of type 'TClasses'

```ts
const blueButton = tw(
  button,
  "rounded-b-full",
  "bg-blue-default",
  hover("bg-blue-lighter"),
  sm("rounded-b-none"),
  sm("rounded-r-full")
);
```

**Comment by muhammadsammy** [comment]
Are you importing from the npm package?
You should import from the generated file instead of the package

**Comment by muhammadsammy** [comment]
> Another issue, I'm getting the following two errors when trying to use my custom colors:
> 
> > tsserver 2345] [E] Argument of type '"bg-blue-default"' is not assignable to parameter of type 'TArgs'
> > tsserver 2345] [E] Argument of type '"bg-blue-lighter"' is not assignable to parameter of type 'TClasses'
> 
> code:
> 
> ```ts
> const blueButton = tw(
>   button,
>   "rounded-b-full",
>   "bg-blue-default",
>   hover("bg-blue-lighter"),
>   sm("rounded-b-none"),
>   sm("rounded-r-full")
> );
> ```
> 
> related types:
> 
> ```ts
> export type TBackgrounds =
>   | TBackgroundAttachment
>   | TBackgroundColor
> 
> export type TClasses =
>   | TUtility
>   | TLayout
>   | TTypography
>   | TBackgrounds
> 
> export type TArgs<T extends TClasses> =
>   | T
>   | null
>   | undefined
>   | { [key in T]?: boolean }
>   | TTailwindString;
> 
> export type TPseudoClass<T extends TClasses = TClasses> = (
>   className: T
> ) => TTailwindString;
> 
> export const hover: TPseudoClass = (className) =>
>   ("hover:" + className) as TTailwindString;
> ```
> 
> It looks like the file generated by running `lib/cli.js` is not found by tsserver ?

Are you importing from the npm package?
You should import from the generated file instead of the package.
