### ISSUE TITLE
Generate lib types for every release

### ISSUE THREAD

**Issue by muhammadsammy** [muhammadsammy/tailwindcss-classnames#172]
types in `src/index.ts` should be automatically generated for every release instead of manually running `yarn generate` manually

**Comment by imrishabh18** [comment]
Does adding this yarn generate command in the release script would do?

**Comment by muhammadsammy** [comment]
The release script is no longer used. instead, releases are automated by release-please GitHub action in https://github.com/muhammadsammy/tailwindcss-classnames/blob/master/.github/workflows/release.yml

So this would be done by adding steps for running yarn generate before releasing and commiting the changes made in the workflow (to src/index.ts).

**Comment by muhammadsammy** [comment]
maybe another simpler solution is to add a GitHub workflow that runs for every push to master 
to generate src/index.ts with yarn generate and committing the changes
