### ISSUE TITLE
Extended spacing is ignored in generated TMargin, THeight and others

### ISSUE THREAD

**Issue by DaDom** [muhammadsammy/tailwindcss-classnames#222]
## Environment:

- `TailwindCSS` version: irrelevant
- `tailwindcss-classnames` version: 2.1.2
- `Node.js` version: 16.0.0

## How to Reproduce
I cloned the master branch and created a minimal file called `tailwind.config.js` in the root directory:
`module.exports = {
  theme: {
    extend: {
      spacing: {
        0.1: '0.025rem'
      }
    }
  }
}`

Now run `yarn run-cli` or `npm run run-cli` as per documentation. The CLI tool will generate a file called `tailwindcss-classnames.ts` in the root directory.

## Expected Behavior
As you see above, my minimal tailwind config extends the default spacing by a new value `0.1`.
My expectation is that all generated types that are based on `spacing` contain a literal with this `-0.1` ending.
In particular, I am expecting:
- `m-0.1`, `mt-0.1`, `mb-0.1`, `ml-0.1`, `mr-0.1`, `mx-0.1`, `my-0.1` and all negative versions of those for `TMargin`
- `h-0.1` for `THeight`
- `inset-0.1`, `bottom-0.1`, etc. for `TInset`
- `max-h-0.1` for `TMaxHeight`
- `p-0.1`, `pt-0.1`, etc. for TPadding
- `space-x-0.1` and `space-y-0.1` for `TSpace`
- `gap-0.1`, etc. for `TGap`
- `translate-x-0.1`, etc. for `TTranslate`
- `w-0.1` for `TWidth

## Current Behavior
The generated types contain only the following literals:
- `p-0.1`, `pt-0.1`, etc. for TPadding
- `gap-0.1`, etc. for `TGap`
All other types ignore this extension and do not contain these literals.
In my current project I have explicitly been missing the margin literals in `TMargin` like `m-0.1` etc.

## Possible solutions (Optional)
My hunch is that the problem is in using the spread-operator in the `defaultTailwindConfig.ts`.
The overwrite of the `extend` settings over the default config currently happens [here](https://github.com/muhammadsammy/tailwindcss-classnames/blob/master/src/cli/core/TailwindConfigParser.ts#L105).
lodash.merge is used to write theme.extend.spacing into theme.spacing.
For example for `padding`, the spread operator is not used in the default config (see [here](https://github.com/muhammadsammy/tailwindcss-classnames/blob/master/src/cli/lib/defaultTailwindConfig.ts#L598)), but for all keys that are ignoring the extension, it is used (for example for margin [here](https://github.com/muhammadsammy/tailwindcss-classnames/blob/master/src/cli/lib/defaultTailwindConfig.ts#L509)).
In the case of padding, this means that [here](https://github.com/muhammadsammy/tailwindcss-classnames/blob/master/src/cli/core/TailwindConfigParser.ts#L105) the `spacing` of the core and the `spacing` of the theme extension are referentially equal, and the merge operation changes both equally. For keys for which the spread-operator was used this is not the case. 

I am pretty sure that this is the root cause behind issue #57 as well.
Please let me know if you'd accept a pull request to fix this.

## Additional Questions

- [x] I've searched the issues list and this is not a duplicate
- [x] I'm willing to fix this error

**Comment by DaDom** [comment]
Probably #63 is the same issue I think, sorry for that.
Feel free to close either issue and we can continue the thread in whatever issue you leave open.

**Comment by muhammadsammy** [comment]
Thanks, @DaDom for the your interest and the detailed description!
>I am pretty sure that this is the root cause behind issue #57 as well.
>Please let me know if you'd accept a pull request to fix this.
>
That would be great :+1:. I'm going to assign you to this issue. Thank you!
