### ISSUE TITLE
Missing classes from CLI

### ISSUE THREAD

**Issue by Shahaed** [muhammadsammy/tailwindcss-classnames#228]
## Environment:

- `TailwindCSS` version: 2.1.2
- `tailwindcss-classnames` version: 1.9.0
- `Node.js` version: 14.4

## Current Behavior
When using the CLI to generate a custom type file from `tailwind.config.js` extended colors are generated for some classes but not others.

Ex tailwind config:
```js
module.exports = {
  mode: "jit",
  purge: ["./pages/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        transparent: "transparent",
        current: "currentColor",
        brand: colors.cyan,
      },
};
```
produces an output from the CLI with types from `bg-brand-500` etc, but does not have `border-brand-500`.

## Expected Behavior
All classes be produced in the type file.

## Additional Questions

- [ x ] I've searched the issues list and this is not a duplicate

**Comment by muhammadsammy** [comment]
Thank you for reporting!

**Comment by muhammadsammy** [comment]
Thank you for reporting!
You should update to v2.1.3 because it contains fixes for a lot of other issues with the extend object.
