### ISSUE TITLE
JIT: Add universal shorthand color opacity syntax

### ISSUE THREAD

**Issue by muhammadsammy** [muhammadsammy/tailwindcss-classnames#239]
([#4348](https://github.com/tailwindlabs/tailwindcss/pull/4348))

**Comment by bstro** [comment]
> I'm not sure if this feature is implemeted in TailwindCSS v2 or not. If it is, please tell me to reopen this issue

I'm running Tailwind 2.2.x and I use the opacity shorthand often. I think this issue could be reopened. Here's the [announcement post for 2.2](https://blog.tailwindcss.com/tailwindcss-2-2#shorthand-color-opacity-syntax) on their blog, which introduces the syntax.
