### ISSUE TITLE
Using the CLI, generating custom classnames creates a tailwindcss-classnames.ts file  that is over 100MB

### ISSUE THREAD

**Issue by Dandandans** [muhammadsammy/tailwindcss-classnames#282]
## Environment:

- `TailwindCSS` version: `2.2.16`
- `tailwindcss-classnames` version: `2.2.3`
- `Node.js` version: `14.15.5`

## Current Behavior
After migrating Tailwind to JIT mode, using the CLI to generate custom classnames ouputs a `tailwindcss-classnames.ts` file that is over 112 MB. The previous size is 858 KB. 

## Expected Behavior

Generate a reasonably sized classnames file. 

## How to Reproduce

Run `tailwindcss-classnames -i tailwind.config.js -x custom-tailwind-classes.ts -o tailwindcss-classnames.ts` to generate classnames. 

## Additional Questions

- [X] I've searched the issues list and this is not a duplicate
- [ ] I'm willing to fix this error

**Comment by muhammadsammy** [comment]
Making the file ignored by Git and generating it automatically by prestart does not actually solve the whole problem, but it solves version control problem with large files. 

Also as @Dandandans [suggested](https://github.com/muhammadsammy/tailwindcss-classnames/pull/281#discussion_r731682711), File size can be reduced with this alternative approach
