### ISSUE TITLE
Create utility functions to separate classnames by categories

### ISSUE THREAD

**Issue by muhammadsammy** [muhammadsammy/tailwindcss-classnames#293]
# Summary
## This will improve performance of autocompletion in addition to organizing classnames by categories

example:
```ts
classnames(
	textColor("text-black", "hover:text-red-600", "active:text-red-800"),
	display("flex", "md:block"),
	flexDirection("flex-row-reverse"),
)
```

- [x] I'm willing to implement this feature

**Comment by hydRAnger** [comment]
Will there be a chance to define this on/off?
I mean use categories as default, but let the user disable it (then 'show autocompletion of all classnames as early version).

**Comment by hydRAnger** [comment]
It's truly conveient, but does the user need to pay more attention to extra information(regularClassGroupKeys)?

**Comment by muhammadsammy** [comment]
@hydRAnger 
Sorry for the late reply!
The problem is that tailwindcss@v3 has JIT mode on all the time which generates a huge number of classnames that make the generated file over 100mb and TS engine can't handle them, the autocompletion and validation does not work with all classnames loaded at once

**Comment by hydRAnger** [comment]
> @hydRAnger Sorry for the late reply! The problem is that tailwindcss@v3 has JIT mode on all the time which generates a huge number of classnames that make the generated file over 100mb and TS engine can't handle them, the autocompletion and validation does not work with all classnames loaded at once

@muhammadsammy 

got it, thanks for the details.
sure, if so, that seems trade-off we need to accept(at least for this moment).

**Comment by muhammadsammy** [comment]
@hydRAnger Hi, I just added more general utility functions like `typography` and `effects` that have more classnames. this could be a useful solution.
eg
typography can have all typography subcategory classnames as font size, font weight, text color, etc 

 #439

**Comment by hydRAnger** [comment]
> @hydRAnger Hi, I just added more general utility functions like `typography` and `effects` that have more classnames. this could be a useful solution. eg typography can have all typography subcategory classnames as font size, font weight, text color, etc
> 
> #439

cool! that's brilliant, let me give it a try 💪

**Comment by oddFEELING** [comment]
Where do I find the list of all categories
