### ISSUE TITLE
Are tailwindcss-classnames releases matching tailwindcss?

### ISSUE THREAD

**Issue by AdrienLemaire** [muhammadsammy/tailwindcss-classnames#31]
Trying again this lib, and having a lot of errors with arguments not assignable to parameter of type 'TArgs<TClasses>' .

Custom tailwind plugins don't seem supported. But also a lot of new tailwindcss utilities.

Is it correct that tailwindcss-classnames only supports tailwind v1.4.0 (we're at v1.7.1 now) ?

**Comment by AdrienLemaire** [comment]
duplicate from #15, I was not importing types from my generated classes but from the node_modules package ^^

**Comment by muhammadsammy** [comment]
> Custom tailwind plugins don't seem supported. 
>
Only [custom-forms](https://github.com/tailwindlabs/tailwindcss-custom-forms) plugin is supported.

>But also a lot of new tailwindcss utilities.
> Is it correct that tailwindcss-classnames only supports tailwind v1.4.0 (we're at v1.7.1 now) ?
>
1.7.0 was just released 23 hours ago :smile:, so yes this package is only compatible with tailwindcss 1.4 for now.

**Comment by AdrienLemaire** [comment]
@muhammadsammy thanks for the quick reply and follow-up <3
Still, it looks like each tailwindcss upgrade requires a lot of work on your part, and they're moving fast! 
Do you think you can keep this up in the long run? 

I was wondering if there wasn't a more generic approach to generate these types.
* If you generate the css file with all classes, you can parse all classes available.
* If you parse the user's custom config file in addition to [tailwind's default config](https://tailwindcss.com/docs/configuration#app), you could use the json object's keys to create group types of utilities.

This way, wouldn't the lib would support any version of tailwindcss and any custom plugin, while requiring less maintenance work on your side?

Else, could you update the README with a tip on how to get custom tailwind plugins types that are unsupported by this lib working in one's project? (in my case, tailwindcss-triangles and tailwindcss-pseudo-elements). Any guideline to help us write these types faster (and maybe contribute to this repo to get these libs supported) would be great.
Thank you very much!
