### ISSUE TITLE
Support arbitrary values

### ISSUE THREAD

**Issue by mariemattick1999** [muhammadsammy/tailwindcss-classnames#321]
# Summary

It would be great if tailwind-classnames would sopport arbitrary values e.g. "text-[#50d71e]"

**Comment by muhammadsammy** [comment]
I don't see how it's possible to support them while having TypeScript validation, however, you can stil add them and cast thier type as a valid type into classnames functions:

```ts
classnames("text-[#50d71e]" as TTailwindString)
```

**Comment by mariemattick1999** [comment]
Ah, didn't know about that. That's fine for me then. Thanks for the fast response. :)
