### ISSUE TITLE
Missing color from TailwindCSS.

### ISSUE THREAD

**Issue by Tarang74** [muhammadsammy/tailwindcss-classnames#363]
## Environment:

- `TailwindCSS` version: 3.0.13
- `tailwindcss-classnames` version: 3.0.1
- `Node.js` version: 14.17.4

## Current Behavior
The color `"bg-zinc-900"` is missing in the package? 
My TypeScript linter says: 
```bash
Argument of type '"bg-zinc-900"' is not assignable to parameter of type 'TArg'. # ts(2345)
```
I get the same error when building the app.
## Expected Behavior
The color should be available in the list of allowed class names.
## How to Reproduce
Just create a React TSX file and the following should create a warning in your IDE:
**index.tsx**
```tsx
import ReactDOM from 'react-dom';
import { classnames } from 'tailwindcss-classnames';

ReactDOM.render(
    <div
        className={classnames(
            'bg-zinc-900' // This line will highlight with an error
        )}
    ></div>,
    document.getElementById('root')
);
```
**index.html**
```html
<!DOCTYPE html>
<html>
<body>
    <div id="root"></div>
</body>
</html>
```
## Possible solutions (Optional)
Could it be because of the release failure?

## Additional Questions

- [x] I've searched the issues list and this is not a duplicate
- [ ] I'm willing to fix this error

**Comment by muhammadsammy** [comment]
Hello!
The `classnames` function does not accept all classnames anymore in v3, but it will accept a utility function of classnames categories:

So the correct way of writing this would be:
```tsx
	<div
        className={classnames(
            backgroundColor('bg-zinc-900')
        )}
    ></div>
```

**Comment by Tarang74** [comment]
@muhammadsammy That makes sense, thank you!

I was going to post another issue but I think it will be easier if I post here, how do I then import the utility functions? I don't want to use the CLI method (as shown in the README.md) because it builds a CSS file with all 24000 classes. When I do this:
```tsx
import { alignItems, classnames } from 'tailwindcss-classnames'; 
```
It asks me whether I meant to do: `TAlignItems`. Is this the same?

**Comment by muhammadsammy** [comment]
That was a bug that was just fixed in https://github.com/muhammadsammy/tailwindcss-classnames/commit/bc47da3288e7a2784f5ed21abe2494ae7a609376
 just update to the latest version and the error will disappear

**Comment by Tarang74** [comment]
Thank you very much for clearing this up!
