### ISSUE TITLE
Missing support for stacking pseudo classes

### ISSUE THREAD

**Issue by bstro** [muhammadsammy/tailwindcss-classnames#368]
## Environment:

- `TailwindCSS` version: ^3.0.15
- `tailwindcss-classnames` version: ^3.0.2
- `Node.js` version: 14.17

## Current Behavior
Using a multiple pseudo classes together throws a type error. 
In this case, I attempted to combine `hover:…` and `active:…`.
![image](https://user-images.githubusercontent.com/627290/149836476-e14dae53-e38d-4b64-9a6d-f6dfb196bd44.png)

## Expected Behavior
I should be able to stack pseudo classes in this way with no type-errors.

- [x] I've searched the issues list and this is not a duplicate
- [ ] I'm willing to fix this error

**Comment by bstro** [comment]
Ah, that makes sense. Is there any kind of escape hatch helper so that I could still use classes like `active:hover:…` without the type system yelling at me? Something like `classnames(backgroundColor('bg-gray-100'), unsafe('active:hover:bg-gray-200)`

**Comment by muhammadsammy** [comment]
yes, you can cast the string to `TTailwindString` type:

```ts
backgroundColor('bg-gray-100', 'active:hover:bg-gray-200' as TTailwindString)
```

**Comment by bstro** [comment]
How would one do that in the case of conditionals?
```
  backgroundColor({
    ['active:hover:bg-gray-200' as TTailwindString]: someConditionalActiveStateBool
  })
```
I spose? I'll write my own helper probably for this case.

Thanks for your help!
