### ISSUE TITLE
Custom screen sizes in config file not working

### ISSUE THREAD

**Issue by Tarang74** [muhammadsammy/tailwindcss-classnames#369]
## Environment:

- `TailwindCSS` version: 3.0.13
- `tailwindcss-classnames` version: 3.0.2
- `Node.js` version: 14.17.4

## Current Behavior
I added a custom screen size in my tailwind.config.js file, but I cannot compile my TS file using the new functional classes in v.3.0.2.
## Expected Behavior
I should be able to use 
```ts
classnames(fontSize('xs:text-3xl', 'sm:text-6xl'))
```
with the following in my config file:
```js
module.exports = {
    theme: {
        extend: {
            screens: {
                'xs': '280px'
            }
        }
    }
};
```
Am I missing something? I could not find much information regarding this in this repository. 

Any help is greatly appreciated!

- [x] I've searched the issues list and this is not a duplicate
- [ ] I'm willing to fix this error

**Comment by muhammadsammy** [comment]
I cannot reproduce this error.
Are you sure you updated the generated file by CLI after you changed the config?

**Comment by muhammadsammy** [comment]
I tried it and it's working fine.
Are you sure you updated the generated file by CLI after you changed the config?

**Comment by Tarang74** [comment]
Ah my bad, I didn't realise I had to use the CLI method, I thought it would work even if I used the node module, thanks I believe that should fix the issue.
