### ISSUE TITLE
Missing 'group' helper?

### ISSUE THREAD

**Issue by bstro** [muhammadsammy/tailwindcss-classnames#371]
## Environment:

- `TailwindCSS` version: 3.0.15
- `tailwindcss-classnames` version: 3.0.2

## Current Behavior
While group pseudo-selectors work file, I am unable to find a helper function for the "group" tailwind class name itself. Its use is [documented here](https://tailwindcss.com/docs/hover-focus-and-other-states#styling-based-on-parent-state)

## Expected Behavior
I would expect something like a `group("group")`. Maybe thats a little awkward, I haven't thought of any alternatives yet.

## Additional Questions

- [x] I've searched the issues list and this is not a duplicate
- [x] I'm willing to fix this error

**Comment by muhammadsammy** [comment]
I noticed that the `peer` classname is also missing. Should the utility contain both?

**Comment by bstro** [comment]
Makes sense to me. What would the helper name be called? I really like how the functions are named after the actual css property, it really helps me use Tailwind faster. in this case, `peer` and `group` don't seem to compile to a css property but rather to selectors. wdyt?

**Comment by muhammadsammy** [comment]
I think you are right. I don't have a name for the helper and if we made one helper, it won't be easy to for the user to figure it out.
