### ISSUE TITLE
Support dark mode

### ISSUE THREAD

**Issue by pspeter3** [muhammadsammy/tailwindcss-classnames#39]
Tailwind is adding dark mode for v2 and is currently experimental.

**Comment by pspeter3** [comment]
I think this can be handled by adding the right experimental flags to the configuration before running generate.

**Comment by muhammadsammy** [comment]
The CLI should generate the `dark:` prefix for classes if it's added to the [screens](https://tailwindcss.com/docs/breakpoints#dark-mode) property in the tailwing config. 
Or does it require other configurations?

**Comment by pspeter3** [comment]
I think that's probably right. We can close this out when dark mode is officially launched. Probably Tailwind v2 or v1.8?
