### ISSUE TITLE
How is src/index.ts created?

### ISSUE THREAD

**Issue by pspeter3** [muhammadsammy/tailwindcss-classnames#40]
I see that you have a CLI to generate the class names. Are you using that for `src/index.ts` as well? Or is that hand written?

**Comment by muhammadsammy** [comment]
Yes, It's generated from the CLI

**Comment by pspeter3** [comment]
Should I have changed another file for #38? Eg, a template then?

**Comment by pspeter3** [comment]
Also, is there a npm script for that? I don't see one in the build pipeline and I don't see Tailwind as a dev dependency.

**Comment by muhammadsammy** [comment]
> Should I have changed another file for #38? Eg, a template then?
>
yup in the template file here: https://github.com/muhammadsammy/tailwindcss-classnames/blob/b736efa04e83e15fffee9e81c4fc714efdf9237b/src/cli/utils/baseTemplateString.ts#L40


> Also, is there a npm script for that? I don't see one in the build pipeline and I don't see Tailwind as a dev dependency.
>
I run it manually on a default tailwind config for every release, but it should be done automatically
There is no tailwind dev dependency because the CLI generates the classes from the tailwind config file.

**Comment by pspeter3** [comment]
> yup in the template file here:

Thanks! I'll update #38 accordingly then.

> I run it manually on a default tailwind config for every release, but it should be done automatically

I'm happy to add a script for this. Maybe as `prebuild`?

> There is no tailwind dev dependency because the CLI generates the classes from the tailwind config file.

What config does it use by default?

**Comment by muhammadsammy** [comment]
> I'm happy to add a script for this. Maybe as `prebuild`?
> 
very nice, thank you!

> What config does it use by default?
>
the one generated by tailwind CLI [here](https://tailwindcss.com/docs/installation#create-your-tailwind-config-file)
`npx tailwindcss init --full`

**Comment by pspeter3** [comment]
Once #41 and #42 are merged, I'll submit a PR with the results of `npm run generate`. I likely think we'll need to bump to v1.7.2 to match Tailwind though.

**Comment by muhammadsammy** [comment]
>  I likely think we'll need to bump to v1.7.2 to match Tailwind though.
>
I agree. this will remove confusion about compatibility with tailwindcss!
