### ISSUE TITLE
missing group-focus types

### ISSUE THREAD

**Issue by AdrienLemaire** [muhammadsammy/tailwindcss-classnames#53]
```js
module.exports = {
  ...
  variants: {
    visibility: ["responsive", "hover", "focus", "group-hover", "group-focus"],
  }
};
```

The generated types contain the group-hover types, but not the group-focus ones:
```ts
export type TPseudoClasses =
  ...
  | 'group-hover:visible'
  | 'group-hover:invisible'
```

![](https://i.imgur.com/YDKTBYq.png)

As per [the documentation](https://tailwindcss.com/docs/pseudo-class-variants#group-focus), group-focus works just like group-hover, so should their types :)

**Comment by muhammadsammy** [comment]
Can't reproduce. It works fine with the same options:
```js
variants: {
  visibility: ["responsive", "hover", "focus", "group-hover", "group-focus"],
}
```

![Screenshot from 2020-09-14 12-03-45](https://user-images.githubusercontent.com/35064832/93072902-5fb37800-f682-11ea-9fa7-d33f67358a22.png)

**Comment by AdrienLemaire** [comment]
Sorry, I don't know what happened ^^' works fine now, closing :bow:

**Comment by AdrienLemaire** [comment]
@muhammadsammy actually I still have an issue. When enabling the `group-hover` or `group-focus` variants, we need to add the `.group` class as well, but it is not added to the types.

https://tailwindcss.com/docs/pseudo-class-variants#group-hover

> If you need to style a child element when hovering over a specific parent element, add the .group class to the parent element and add the group-hover: prefix to the utility on the child element.

```console
$ cat src/utilities/tailwind.ts|grep group
  | 'group-hover:visible'
  | 'group-focus:visible'
  | 'group-hover:invisible'
  | 'group-focus:invisible'
```

**Comment by AdrienLemaire** [comment]
@muhammadsammy really sorry ^^ The fix in  dbf7f20 doesn't seem correct. 

Given conf
```js
    visibility: ["responsive", "hover", "focus", "group-focus"],
```
I get
```console
$ cat src/utilities/tailwind.ts|grep group
  | 'group'
  | 'group-focus:invisible'
```
the `group-focus:visible` utility is missing.

Given conf
```js
    visibility: ["responsive", "hover", "focus", "group-hover", "group-focus"],
```

I get 
```console
cat src/utilities/tailwind.ts|grep group
  | 'group'
  | 'group-focus:visible'
  | 'group-hover:invisible'
  | 'group-focus:invisible'
```
the `group-hover:visible` utility is missing.


It looks like the `group` utility replaces the first generated rule instead of being added.

**Comment by muhammadsammy** [comment]
added a fix in 7381d13, v1.8.2

**Comment by AdrienLemaire** [comment]
@muhammadsammy thanks for being so fast! LGTM

**Comment by muhammadsammy** [comment]
Glad to help!
