### ISSUE TITLE
Looking for Maintainers

### ISSUE THREAD

**Issue by muhammadsammy** [muhammadsammy/tailwindcss-classnames#62]
Hello and thanks to all contributors and users of this project!

Unfortunately, I will not be able to maintain this project well for the next three months.
If anyone is interrested in becoming a maintainer, please [contact me](mailto:themsammy@outlook.com)!

**Comment by AdrienLemaire** [comment]
I won't be able to maintain the repo, but I really hope that someone else can take this over. Otherwise, I look forward to you coming back in 3 months.
It would be great if @adamwathan and @reinink could consider sponsoring this repo or integrating in to tailwindcss for official typescript support.

**Comment by stemount** [comment]
@muhammadsammy I'd definitely be looking into this being put in upstream should it work with more than just React(????).

1. How much work is maintenance of this project per month?
2. I'd volunteer some time here for pull request review.
3. I opened up to the @eddiejaoude community to find maintainers

Awesome work on it gaining traction!

![image](https://user-images.githubusercontent.com/150512/98362475-2fa2a880-2025-11eb-8c15-75114fc5a867.png)

**Comment by muhammadsammy** [comment]
@stemount 

> 1. How much work is maintenance of this project per month?
> 

It depends on how many features in a tailwindcss release and how frequent they release a new version. However, it's not really a lot of time, but I'm very busy taking MBBS exams for the next 3 months.

> 2. I'd volunteer some time here for pull request review.
> 

That's awesome. Thank you! I've sent you an invite.

> 3. I opened up to the @eddiejaoude community to find maintainers
> 

That's very nice! Really appreciate it

**Comment by laniakea-landscape** [comment]
Hello.
I cant help in TypeScript, but I have a question.
Where are you taking full class list? I need it for Elm package. To be honest, for previous version I parsed your index.ts.
But now Tailwind CSS 2.0.1 released and I have new project on it. So, can you share your secret?
Thank you.

**Comment by muhammadsammy** [comment]
Thanks @laniakea-landscape for your interest!

I get the new changes from their [release notes](https://github.com/tailwindlabs/tailwindcss/releases/tag/v2.0.0).
Then the list of types in `src/index.ts` gets generated by the CLI:

First thing is to update tailwindcss and the default config file by running: 

```bash
yarn add -D tailwindcss@^2.0.1 autoprefixer
yarn run updateConfig
```

This will update [`src/cli/lib/defaultTailwindConfig.ts`](https://github.com/muhammadsammy/tailwindcss-classnames/blob/develop/src/cli/lib/defaultTailwindConfig.ts) with the latest tailwind config
The CLI will use this file to generate these classes automatically:
- new [pseudoclass variants](https://github.com/muhammadsammy/tailwindcss-classnames/blob/61913c02330efdb746ba6da9a2464ca64ed6471c/src/cli/core/ClassesGenerator.ts#L317) e.g. `hover:flex`, `focus:flex`, `md:flex` etc.
- new classnames that are based on new _values_ in config. e.g. in tailwind v2 they added font sizing like `text-7xl`. the new config will have this value and thus will be [generated by the CLI](https://github.com/muhammadsammy/tailwindcss-classnames/blob/61913c02330efdb746ba6da9a2464ca64ed6471c/src/cli/core/ClassesGenerator.ts#L305).

---

The above will update _existing_ classes that got new _vlaues_. 
Other new added class _names_ will be divided into:
 
 - classes that their name cannot be changed should be added to [`src/cli/lib/non-configurable/CORRESPONDING_CATEGORY.ts`](https://github.com/muhammadsammy/tailwindcss-classnames/tree/develop/src/cli/lib/non-configurable).
 An example for these would be `flex`, `block` (non-configurable/layout) or `capitalize` (non-configurable/typography).

- classes that their name can be modified (like `bg-red-100`, sizing classes `w-6`, etc.) each should be added to corresponding category method in [`ClassesGenerator` class](https://github.com/muhammadsammy/tailwindcss-classnames/blob/develop/src/cli/core/ClassesGenerator.ts).

---

After doing this for new classes, the CLI is compatible with new tailwind release.
Now update `src/index.ts` file with the new types by running `yarn generate`.

---

for testing the CLI (should add tests in the future):
1. build the project: `yarn build`
2. generate a tailwind config for testing: `yarn run tailwindcss init --full` and change configs according to new classes.
3. run the CLI on the tailwind config: 
`node ./lib/cli/index.js -c tailwind.config.js -o path/to/output/file.ts` 
and see the output file.

**Comment by muhammadsammy** [comment]
I'm closing this as I'm going to continue maintaining the project. 
Just a day ago, my country postponed all exams due to increased covid cases, so I will have some time until Feb.

The support for tailwindcss v2 progress will be tracked at #66
