### ISSUE TITLE
Merge `extend` objects deeply by default 

### ISSUE THREAD

**Issue by muhammadsammy** [muhammadsammy/tailwindcss-classnames#88]
([#2679](https://github.com/tailwindlabs/tailwindcss/pull/2679))

**Comment by femialaka** [comment]
Hi, I would like to get stuck in can you tell me how to set up locally on a Mac.  For example do I create a link to the cloned version? I setup a react project in Typescript and created a link from the cloned version of Tailwindcss-classnames to the app but got the following error:

npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/tailwindcss-classnames/lib/cli/index.js'
npm ERR! enoent This is related to npm not being able to find a file.

can you help with this please.

**Comment by muhammadsammy** [comment]
Sure! You can now invoke the cli by running `yarn run-cli` or `npm run run-cli`inside the repo source and it will prompt you with questions. 
You have to pull the latest changes as I just added this npm script here 86e5eb9a150cb1244d22659321175ef21b500795 .
Do'nt hesitate to ask about anything confusing and thanks for your interrest!

**Comment by DaDom** [comment]
Was this change already implemented, but the issue not closed?
As far as I can see the generation already works according to this change in tailwindcss.

For example, if I use the following basic tailwind configuration:

```javascript
module.exports = {
  theme: {
    extend: {
      colors: {
        red: {
          5000: '#FF0000'
        }
      }
    }
  }
}
```

Now I run `npm run run-cli` and the resulting `tailwindcss-classnames.ts` contains:

```
...
export type TTextColor =
    ...
    | 'text-red-50'
    | 'text-red-100'
    | 'text-red-200'
    | 'text-red-300'
    | 'text-red-400'
    | 'text-red-500'
    | 'text-red-600'
    | 'text-red-700'
    | 'text-red-800'
    | 'text-red-900'
    | 'text-red-5000'
    ...
```

This looks like a correct deep-merge to me, or did I misunderstand the issue?

**Comment by muhammadsammy** [comment]
I think you're right :+1:. I will close this. Thank you!
